### ISSUE TITLE
terrorist

### ISSUE THREAD

**Issue by TwurlNo1RLplayerOCE** [waleedf112/WaleedAlenazi.com#1]
saudi arabia is a terrorist nation
i will never forget 9/11

**Comment by OPisFGTET** [comment]
alllahuuuuu akbarrrrrrrrr

**Comment by TwurlNo1RLplayerOCE** [comment]
i support biden nuking riyadh and turning it into glass

**Comment by waleedf112** [comment]
You guys are pathetic.

Reported to GitHub support.

**Comment by OPisFGTET** [comment]
rEpOrTeD to ISIS
